oute:
  group_by: ['alertname', 'job', 'instance','severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5h
  receiver: '<clientAccountName>'
  routes:
    - match:
        alertname: HostMemoryTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: HostMemoryTroubleResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: HostMemoryCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: HostHighCpuLoadTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: HostHighCpuLoadCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: HostHighCpuLoadResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: HostHighSwapUsageTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: HostHighSwapUsageCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: HostHighSwapUsageResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: DiskIOHighCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: DiskIOResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: HostDiskUtilizationTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: HostDiskUtilizationCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: HostDiskUtilizationResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: HostDiskPartitionUsageTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: HostDiskPartitionUsageCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: HostDiskPartitionUsageResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceCPUTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceCPUCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceCPUResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceLowBurstBalanceTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceLowBurstBalanceCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceBurstBalanceResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceLowFreeableMemoryTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceLowFreeableMemoryCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceFreeableMemoryResolved
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceHighConnectionCountTrouble
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceHighConnectionCountCritical
      receiver: '<clientAccountName>'
    - match:
        alertname: RDSInstanceConnectionCountResolved
      receiver: '<clientAccountName>'
 
    # Add more alertname and receiver configurations as needed
 
receivers:
  - name: '<clientAccountName>'
    webhook_configs:
      - url: '<insert_url_here>'
        http_config:
          authorization:
            credentials: <insert_credentials_here>
        send_resolved: true

# Inhibition Rule to suppress trouble alerts when critical alerts are present
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'trouble'
    equal:
      - alertname
